[book]
authors = ["peter"]
language = "cn"
multilingual = false
src = "src"
title = "Polos MCU开发板使用指南"


[build]
build-dir = "../docs/polos/"
# create-missing = true

[output.html]
sidebar = true  # 关键配置：强制显示侧边栏（禁用自动隐藏）
